title: FoodHyper
subtitle: Der FoodHyper ist ein Programm zur Förderung von Food-Startups in Niedersachsen!
baseurl: /
permalink: "/:year/:month/:day/:title/"
# Google Analytics
google_analytics: G-4MM29SQSZG
collections:
  posts:
    permalink: "/blog/:year/:month/:day/:title/"

header:
  title: FoodHyper
  logo_img: images/logo.png
  has_nav: true
  nav:
    Allgemeines: "foodhyper"
    Hackathon: "hackathon"
    Bootcamp: "bootcamp"
    FoodLaw: "law"
    News: "blog"
    Foodpaten: "foodpaten"
    FAQ: "faq"
  palette: blue
  
footer:
  logo_img: images/foodhyper_white.png
  tagline: 
  content: "&copy; Seedhouse Accelerator GmbH. All rights reserved."
  links:
    - text: Impressum
      url: "/impressum"
      new_window: false
    - text: Datenschutz
      url: "/datenschutz"
      new_window: false

  social_title: Social Media

  nav_title: Navigation
  nav:
    FoodHyper: "foodhyper"
    Hackathon: "hackathon"
    Bootcamp: "bootcamp"
    Law: "law"
    News: "blog"
    Foodpaten: "foodpaten"

  has_subscribe: true
  subscribe_title: "Interesse?"
  subscribe_content: "Dann schreibe uns gerne!"

defaults:
  -
    scope:
      path:            "drafts/**"
    values:
      sitemap:         false
  -
    scope:
      path:            "images/**"
    values:
      sitemap:         false

sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
