title: Foodhyper
baseurl: /
permalink: "/:year/:month/:day/:title/"
# Google Analytics
google_analytics: G-W1PBP2W25B
collections:
  posts:
    permalink: "/blog/:year/:month/:day/:title/"

header:
  title: Foodhyper
  logo_img: images/logo.png
  has_nav: true
  nav:
    Foodhyper: "foodhyper"
    Hackathon: "hackathon"
    Bootcamp: "bootcamp"
    FoodLaw: "law"
    Blog: "blog"
  palette: blue
  menu:
    actions:
      - label: Interesse?
        url: /contact
footer:
  logo_img: images/logo.png
  tagline: 
  content: "&copy; MMM Intelligence UG (haftungsbeschränkt). All rights reserved."
  links:
    - text: Impressum
      url: "/impressum"
      new_window: false
    - text: Datenschutz
      url: "/datenschutz"
      new_window: false

  social_title: Community

  nav_title: Company
  nav:
    Foodhyper: "foodhyper"
    Hackathon: "hackathon"
    Bootcamp: "bootcamp"
    Law: "law"
    Blog: "blog"

  has_subscribe: true
  subscribe_title: "Interesse?"
  subscribe_content: "Hier Kontakt aufnehmen"

defaults:
  -
    scope:
      path:            "drafts/**"
    values:
      sitemap:         false
  -
    scope:
      path:            "images/**"
    values:
      sitemap:         false

sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
